### ISSUE TITLE
incomplete snacbar when not authorized to data

### ISSUE THREAD

**Issue by JoepGrispen** [nens/G4AW-lizard-client#175]
When i am authorized to log in to Lizard but not in the vietnam group I can select a parcel but the client gives no feedback in the snackbar. 

In otrher words people with a lizard account how log in to the client think that it does not work

**Comment by JoepGrispen** [comment]
When i select login i am redirected to the SSO page. After confirming login en password I am in the webclient but when I go back in historie and land on the SSO page again after confirmation I am redirected to demo.lizard.net

**Comment by d-weeteling** [comment]
I have discussed this with Remco and we thought of a solution that is quite easy:

On initial load we check whether a user (who is already authenticated) can find more than 0 parcels in the spatial extent for Vietnam (via hydra-core search endpoint). If this is not the case we can show a snackbar message to the user, indicating he hasn't got the correct permissions. If hydra-core returns more than 0 searchresults, we don't inform the user because the app works as expected.

**Comment by Derryrover** [comment]
archive repo
